---
galaxy_info:
  role_name: ocp_install_upi
  namespace: lit
  author: Dirk Egert
  description: UPI-based OpenShift installation logic.
  company: degert-it
  license: GPL-2.0-only
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"
dependencies: []
