---
- name: Wait for install complete agent based
  delegate_to: "{{ ocp_install_delegate_to }}"
  run_once: true
  ansible.builtin.command:
    cmd: >-
      {{ ocp_install_cluster_sub_dirs.download }}/openshift-install
      agent wait-for install-complete
      --dir {{ ocp_install_cluster_sub_dirs.config }}
  changed_when: false
  retries: 60
  delay: 60
